spring:
  application.name: TechTrack
  datasource:
    username: postgres
    password:
    url: jdbc:postgresql://localhost:5432/trackdb
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

